# Generated by Django 4.2.5 on 2024-10-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_interest_course_interests_userprofile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
